services:
  itkeller-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: itkeller-website
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - "3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
